### ISSUE TITLE
🪲 Bug report Edit-WinGetSettings fails with EditorPath

### ISSUE THREAD

**Issue by jdhitsolutions** [SamErde/PSPreworkout#22]
I can see you are trying to give the user an editor option with `Edit-WinGetSettings`, but I think there is a bug with the `-EditorPath` parameter. I thought I could run `Edit-WingetSettingsFile -EditorPath notepad.exe` but VSCode opened instead. Then I tried `edit-WingetSettingsFile -EditorPath (Get-Item c:\windows\notepad.exe)` since you've cast the type as `[FileInfo]`. Still no. 

I think the issue is in this code:

```powershell
if ($PSBoundParameters.ContainsKey($EditorPath)) {
            Start-Process $EditorPath $WinGetSettingsFile
        } 
```

You are testing for the *parameter value`, not the parameter name: 

```powershell
$PSBoundParameters.ContainsKey('EditorPath')
```

I'd recommend using parameter sets for `-VSCode` , `-Notepad` and `-EditorPath`.  You could make the VSCode parameter set the default.

**Comment by SamErde** [comment]
Wanted to get a fix out, so I removed the **EditorPath** parameter for v1.4.9 and just put in checks for the most likely available editors on Windows computers (code, notepad.exe, Notepad UWP, PowerShell ISE).
