### ISSUE TITLE
🪲 Bug report Incorrect PowerShell version

### ISSUE THREAD

**Issue by jdhitsolutions** [SamErde/PSPreworkout#3]
The module manifest requires PowerShell version 5.2. I don't know what you're running, but if this supports Windows PowerShell the value should be 5.1.

**Comment by SamErde** [comment]
Wow, thanks, Jeff! That was a misplaced '2' when I bumped the version of the *module* from 5.1 to 5.2! I just fixed and re-published. 🙏💙

**Comment by SamErde** [comment]
I only wish I had access to a preview release of Windows PowerShell 5.2! 😂

**Comment by SamErde** [comment]
![image](https://github.com/user-attachments/assets/0dee10fe-06e9-4b86-8d03-14eb88b03a52)
